# Generated by Django 5.1.1 on 2024-09-12 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shopentry_rating_shopentry_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
